secrets_filepath = ".env"

[mqtt.broker]
hostname = "10.0.0.3"
port = 1_883
timeout = 5

[mqtt.node_network]
topic_structure = "machine/module/measurement/field*"
enable_prometheus_server = true
prometheus_port = 8_001

[mqtt.node_client]
subscribe_topic = "sensor_network/#"
node_id = "mqtt-node-client-0"
influx_config = "config/.influx_live.toml"
qos = 0

